secret_key_base: XYZ

database:
  name:
    development: "transparency_hub_dev"
    production: "transparency_hub"
  user:
    development: "transparency_hub_dev"
    production: "transparency_hub"
  password:
    development: 12345678
    production: ""                      


# If using capistrano for deploying, fill out these aswell

# production:
#  server:
#    user: ""
#    domain: ""




