
default: &default
  adapter: <%= ENV['DATABASE_TYPE'] %>
  encoding: unicode
  pool: 5
  host: <%= ENV['DATABASE_HOST'] %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  database: <%= ENV['DATABASE_NAME'] %>

development:
  <<: *default

test:
  <<: *default

# # As with config/secrets.yml, you never want to store sensitive information,
# # like your database password, in your source code. If your source code is
# # ever seen by anyone, they now have access to your database.
# #
# # Instead, provide the password as a unix environment variable when you boot
# # the app. Read http://guides.rubyonrails.org/configuring.html#configuring-a-database
# # for a full rundown on how to provide these environment variables in a
# # production deployment.

production:
  <<: *default
