
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost

development:
  <<: *default
  database: <%= Rails.application.credentials.dig :database, :name, :development %>
  username: <%= Rails.application.credentials.dig :database, :user, :development %>
  password: <%= Rails.application.credentials.dig :database, :password, :development %>


test:
  <<: *default
  database: transparency_hub_test

# As with config/secrets.yml, you never want to store sensitive information,
# like your database password, in your source code. If your source code is
# ever seen by anyone, they now have access to your database.
#
# Instead, provide the password as a unix environment variable when you boot
# the app. Read http://guides.rubyonrails.org/configuring.html#configuring-a-database
# for a full rundown on how to provide these environment variables in a
# production deployment.

production:
  <<: *default
  database: <%= Rails.application.credentials.dig :database, :name, :production %>
  username: <%= Rails.application.credentials.dig :database, :user, :production %>
  password: <%= Rails.application.credentials.dig :database, :password, :production %>
